# Generated by Django 6.0.3 on 2026-04-12 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalyzeRequest",
        ),
    ]
